version: '3'

services:
  php:
    build: ./php
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ../src:/var/www/html

  nginx:
    image: nginx
    ports:
      - 8888:80
    volumes:
      - ../src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./mysql/my.cnf:/etc/mysql/conf.d/my.cnf
      - ../db/data:/var/lib/mysql
      - ../db/sql:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
#  db:
#    image: postgres:14-bullseye
#    environment:
#      POSTGRES_USER: user
#      POSTGRES_PASSWORD: password
#      PGPASSWORD: root
#      POSTGRES_DB: app
#      PGDATA: /var/lib/postgresql/data/pgdata
#      TZ: "Asia/Tokyo"
#    ports:
#      - 5432:5432
#    volumes:
#      - ./db/data:/var/lib/postgresql/data

  node:
    image: node:14.18-buster-slim
    tty: true
    volumes:
      - ../src:/var/www/html
    working_dir: /var/www/html

  mail:
    image: mailhog/mailhog
    ports:
      - 8025:8025

  minio:
    image: 'minio/minio'
    container_name: minio
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin123
    entrypoint: bash
    command: -c "/opt/bin/minio server /export --address :9999 --console-address :9001"
    volumes:
        - ../minio:/export
    ports:
        - '9000:9999'
        - '9001:9001'